version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: "npm start"
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0